"""drop embedded flag from audio_metadata

Revision ID: 2165a2ed1c8a
Revises: e71bb17ecc73
Create Date: 2026-03-11 15:04:23.875195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2165a2ed1c8a'
down_revision: Union[str, Sequence[str], None] = 'e71bb17ecc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
