"""remove transcribed flag from audio-metadata

Revision ID: 30fc1b714461
Revises: b5f776e9c148
Create Date: 2026-04-18 19:34:20.059051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fc1b714461'
down_revision: Union[str, Sequence[str], None] = 'b5f776e9c148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_metadata', 'transcribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_metadata', sa.Column('transcribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
