"""remove QA, move embedded to transcript

Revision ID: b5f776e9c148
Revises: 2165a2ed1c8a
Create Date: 2026-04-18 18:36:04.085013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5f776e9c148'
down_revision: Union[str, Sequence[str], None] = '2165a2ed1c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_pairs')
    op.drop_column('audio_metadata', 'qa_extracted')
    op.add_column('transcripts', sa.Column('embedded', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'embedded')
    op.add_column('audio_metadata', sa.Column('qa_extracted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('qa_pairs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('qa_pairs_transcript_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['audio_metadata.id'], name=op.f('qa_pairs_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('qa_pairs_pkey'))
    )
    # ### end Alembic commands ###
