"""drop embedded flag from audio_metadata

Revision ID: e71bb17ecc73
Revises: e7b87ed9a676
Create Date: 2026-03-11 15:01:34.235732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71bb17ecc73'
down_revision: Union[str, Sequence[str], None] = 'e7b87ed9a676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_metadata', 'embedded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_metadata', sa.Column('embedded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
